### ISSUE TITLE
Is there a way to rename saved files?

### ISSUE THREAD

**Issue by maukoese** [adonisjs/attachment-lite#10]
Would be nice to specify names/prefixes for uploaded images. 

Something like this

```ts
data.avatar = Attachment.fromFile(avatar, {name: new Date().getTime() + '-avatar'} );
```

**Comment by thetutlage** [comment]
Yup. Can be supported

**Comment by maukoese** [comment]
I think that would be very good, to avoid clashes when multiple users upload similarly named files, and the directory structure is not refined.

**Comment by thetutlage** [comment]
The file is already renamed to random filename. So conflicts are already taken care of.
