### ISSUE TITLE
How to use Factory with a model that implements Attachment Lite?

### ISSUE THREAD

**Issue by madebylydia** [adonisjs/attachment-lite#17]
Hi there! I've been having trouble recently with using [model factories](https://docs.adonisjs.com/guides/models/factories) because of how we can create Attachment objects.
I cannot create an Attachment object because:

1. The image is not on the database
2. I cannot create a MultipartFile object myself apparently

I'm wondering if there's any other way to create an Attachment object? :smiley: If not, you could guide me on what I could PR to help fix this issue?
Thank you.

**Comment by thetutlage** [comment]
Hey, thanks for asking. I have documented the usage with model factories in the README. https://github.com/adonisjs/attachment-lite#using-attachment-lite-with-model-factories

**Comment by madebylydia** [comment]
Awesome! Thanks for your help! ❤️
