### ISSUE TITLE
Files in temp folder are not deleted after uploading to S3.

### ISSUE THREAD

**Issue by aungpyaekyaw** [adonisjs/attachment-lite#20]
File is not deleted after uploading to S3. The uploaded files are also stored in the temp folder.

## Package version
1.0.4

## Node.js and npm version
Nodejs - v14.18.1
npm - 6.14.15

## Sample Code (to reproduce the issue)
Use S3 as disk and upload a file. The same file will exist in the temp folder .

**Comment by thetutlage** [comment]
Please provide the code for reproduction.
