### ISSUE TITLE
Ability to override serialize, prepare and consume options on attachment decorator

### ISSUE THREAD

**Issue by justDare** [adonisjs/attachment-lite#21]
At the moment it is impossible to override the following column options on the attachment decorator: serialize, prepare and consume.

I've found the code where the options are configured here:
<img width="777" alt="Screen Shot 2023-01-18 at 1 02 19 PM" src="https://user-images.githubusercontent.com/28678877/213282932-9c333da2-d994-4814-84da-4098ae6bdbe2.png">

I think the column options should take priority in the spread so we may override them if we choose.

## Why this feature is required (specific use-cases will be appreciated)?
Ability to override serialize, prepare and consume options on the attachment() decorator for more advances serialization cases (ie. omit or not based on model $sideloaded values).

## Have you tried any other work arounds?
No it is impossible to use custom serialize, prepare and consume options on the attachment() decorator as of right now.

## Are you willing to work on it with little guidance?
Absolutely. Easy change.

**Comment by RomainLanz** [comment]
Closing in favor of the PR.
