### ISSUE TITLE
Model `save` function does not return the model anymore

### ISSUE THREAD

**Issue by aa-ndrej** [adonisjs/attachment-lite#26]
When a model contains the `attachment` decorator the `save` function of the model internally calls the `saveWithAttachments` function of the decorator and returns `undefined` instead of `Promise<Model>`.

## Package version
v1.0.7

## Node.js and npm version
Node.js: v18.15.0
npm: v9.5.0

## Sample Code (to reproduce the issue)
Add the `attachment` decorator to a model.

**Comment by hbatalhaStch** [comment]
@thetutlage I am facing the same issue? Any fix or workaround?

**Comment by aa-ndrej** [comment]
@hbatalhaStch the workaround would be to just treat the `save` function as if it is not returning anything.

So instead of chaining `model.save().otherMethod();` use `model.save(); model.otherMethod();`.
Or instead of returning `return model.save()` use `model.save(); return model;`

**Comment by hbatalhaStch** [comment]
@aa-ndrej thanks for the tip.

I have a question though: I am using the return of `model.save()` to check if save was successful, is this a good way? Is there a need to check if save was successful?

**Comment by aa-ndrej** [comment]
@hbatalhaStch you can view the source code of the models `save` function if you navigate to `node_modules/@adonisjs/lucid/build/src/Orm/BaseModel/index.js`. I do not have that much experience with `adonisjs` but as far as I can see the function just returns `return this;`, so it is not really indicating that the model was successfully saved.
But I would assume that the `save` function would throw some kind of error otherwise.

**Comment by hbatalhaStch** [comment]
@aa-ndrej 
> you can view the source code of the models save function...

I already cloned the lucid repo to study to see if it throws somewhere

> but as far as I can see the function just returns `return this;`

I am trying to see if any of the functions called above throws an error
@thetutlage would be helpful here.

Thanks

**Comment by RomainLanz** [comment]
Closing in favor of the [PR](https://github.com/adonisjs/attachment-lite/pull/30).

**Comment by RomainLanz** [comment]
Released as [`1.0.8`](https://github.com/adonisjs/attachment-lite/releases/tag/v1.0.8)
