### ISSUE TITLE
Image conversion after uploading

### ISSUE THREAD

**Issue by guoyunhe** [adonisjs/attachment-lite#28]
## Package version
1.0.7

## Node.js and npm version
18.16.0, pnpm 8.2.0

## Sample Code (to reproduce the issue)

Users often upload very large photos as avatars and we want to resize it and convert to webp to save storage space. However, `Attachment` only created from the `MultipartFileContract` that is directly from `request`. Even I override the file with converted webp, it still store file info of previous PNG/JPG.

```ts
const tempFile = await file();
await sharp(avatar.tmpPath).webp().toFile(tempFile.path);
await rename(tempFile.path, avatar.tmpPath);
auth.user!.avatar = Attachment.fromFile(avatar);
```

Is here a good practice to do image conversion with Attachment? Thanks!

**Comment by ndianabasi** [comment]
If you need image manipulation, have a look at this sister add-on: https://www.npmjs.com/package/adonis-responsive-attachment. It has detailed options for almost any configurations you will need.

**Comment by guoyunhe** [comment]
@ndianabasi I didn't find the feature I need: resize to small size and delete the original file to save storage space...

**Comment by ndianabasi** [comment]
Relax and read through the docs. 

`10. The keepOriginal Option`

**Comment by ndianabasi** [comment]
`3. The breakpoints`

**Comment by RomainLanz** [comment]
Closing since not actionable.
