### ISSUE TITLE
Attachment's name is undefined

### ISSUE THREAD

**Issue by mateusmf4** [adonisjs/attachment-lite#29]
Whenever I make an attachment from an uploaded file the name is always undefined, which causes an error on `getUrl()` and likely other methods. From what I can tell in the code the `fromFile` method never sets the name?

## Package version
1.0.7

## Node.js and npm version
v18.16.0 and 9.5.1

## Sample Code (to reproduce the issue)
```js
const att = Attachment.fromFile(someFile);

console.log(att.name); // undefined

console.log(att.getUrl()); // error
```

**Comment by RomainLanz** [comment]
Hey @mateusmf4! 👋🏻 

Can you please create a repository with the minimum amount of code to reproduce your issue?

**Comment by RomainLanz** [comment]
Closing since no answer from issue reporter.
