### ISSUE TITLE
Unavoidable errors when DB response is `null`

### ISSUE THREAD

**Issue by ndianabasi** [adonisjs/attachment-lite#6]
## Prerequisites

I've noticed a persistent and unavoidable error when DB response is `null`. In a typical usage of the addon, not all attachment column will return the expected format which is parse-able by the add-on. Some columns will contain `null` values. The add-on current fails when `null` values are encountered.

The issue can be traced to these lines: https://github.com/adonisjs/attachment-lite/blob/4f05e55fa752c05293fe6a6465a0e0ecfd83f21e/src/Attachment/index.ts#L64-L75

When `attributes` is `null`, the `Array.forEach` call fails. A suggestion is for the add-on to provide a `no-op` when `null` is encountered.

## Package version
1.0.1

## Node.js and npm version
Node: 14.18.2. NPM: 6.14.15

## Sample Code (to reproduce the issue)
https://github.com/adonisjs/attachment-lite/blob/4f05e55fa752c05293fe6a6465a0e0ecfd83f21e/src/Attachment/index.ts#L64-L75

**Comment by thetutlage** [comment]
Yeah we can ignore explicit `null` values to allow nullable columns
