### ISSUE TITLE
Pre-signed URL saved on model expired 

### ISSUE THREAD

**Issue by aungpyaekyaw** [adonisjs/attachment-lite#9]
## Package version
``` "@adonisjs/attachment-lite": "^1.0.4", ```

## Node.js and npm version
``` Nodejs - v14.18.1 ```
``` npm - 6.14.15```

I'm using with preComputedUrl on private s3 disk to get signed url. The problem is that when a new model is created, the pre-signed url will be saved into the model. 
Because of the expiry on pre-signed url, the url is no longer valid on next access. Is there a way to refresh pre-signed url.
Is it intended behavior or am I doing wrong.
Thanks.

**Comment by thetutlage** [comment]
Can you please share some code, with the actual output you get and the expected output?

**Comment by aungpyaekyaw** [comment]
Hi, Thank you for the reply.

The visibility of my s3 config is set to private. So when I create a new model with preComputeUrl option, the attachment file url will be signed according to documentation.

It stored like the following in database.

`
{"url": "https://s3.ap.amazonaws.com/xxxx/cl2fx7fpe0003jj796udk1k6w.png?signed-params****", "name": "cl2fx7fpe0003jj796udk1k6w.png", "size": 834039, "extname": "png", "mimeType": "image/png"}
`

I can access the resource with the above pre-signed url. The problem is when the pre-signed url expired, attachment-lite is still returning the same pre-signed url and the resource is no longer available..

**Comment by ndianabasi** [comment]
I think the issue is from here:

```ts
/**
     * Self compute the URL if "preComputeUrl" is set to true
     */
    const fileVisibility = await disk.getVisibility(this.name)
    if (fileVisibility === 'private') {
      this.url = await disk.getSignedUrl(this.name)
    } else {
      this.url = await disk.getUrl(this.name)
    }
```

and

```ts
 /**
   * Returns the signed URL for the file. Same as "Drive.getSignedUrl()"
   */
  public getSignedUrl(options?: ContentHeaders & { expiresIn?: string | number }) {
    return this.getDisk().getSignedUrl(this.name, options)
  }
```

We might need to re-generate the signed URL when when the model is fetched.

**Comment by thetutlage** [comment]
Yup. Actually, we shouldn't be saving URL in the database at all and always compute it at runtime. Only the name and other meta data should be saved
